variable "org_id" {}
variable "policy_name" {}
variable "perimeter_name" {}
variable "description" {}
variable "resources" {}
variable "restricted_services" {}
variable "ingress_policies" {}
variable "egress_policies" {}
variable "folder_id" {}
variable "access_level_name" {}
variable "members" {}
variable "regions" {}
variable "ip_subnetworks" {}
