steps:
- id: 'setup cred'
  name: 'alpine'
  entrypoint: sh
  args:
  - -c
  - echo $$SA > $_REPO_PARENT_DIR/key.json && ls $_REPO_PARENT_DIR
  secretEnv: ['SA']
  
- id: 'tf init'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - cd $_REPO_PARENT_DIR && terraform init

- id: 'tf plan'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - cd $_REPO_PARENT_DIR && terraform plan

- id: 'tf apply'
  name: 'hashicorp/terraform'
  entrypoint: 'sh'
  args: 
  - '-c'
  - cd $_REPO_PARENT_DIR && terraform apply --auto-approve

availableSecrets:
  secretManager:
  - versionName: projects/1054492051306/secrets/sa-test/versions/1
    env: 'SA'
